Repository sim-co/daisy-frontend, pull requests merged in 2023-02, with the labels that each got.

#5 Daisy 14 회원정보 입력 screen
  App.tsx
  android/app/src/main/assets/fonts/Pretendard-Black.otf
  android/app/src/main/assets/fonts/Pretendard-Bold.otf
  android/app/src/main/assets/fonts/Pretendard-ExtraBold.otf
  android/app/src/main/assets/fonts/Pretendard-ExtraLight.otf
  android/app/src/main/assets/fonts/Pretendard-Light.otf
  android/app/src/main/assets/fonts/Pretendard-Medium.otf
  android/app/src/main/assets/fonts/Pretendard-Regular.otf
  android/app/src/main/assets/fonts/Pretendard-SemiBold.otf
  android/app/src/main/assets/fonts/Pretendard-Thin.otf
  android/link-assets-manifest.json
  index.js
  ios/MyApp.xcodeproj/project.pbxproj
  ios/MyApp/Info.plist
  ios/Podfile.lock
  ios/link-assets-manifest.json
  package-lock.json
  package.json
  react-native.config.js
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/assets/svgs/camera.svg
  src/assets/svgs/caretDown.svg
  src/assets/svgs/index.js
  src/components/ui/buttons/LoginButton.tsx
  src/constants/Color.ts
  src/redux/AuthSlice.ts
  src/redux/hooks.ts
  src/redux/store.ts
  src/screen/LoginScreen/ButtonContainer/index.tsx
  src/screen/MainScreen/index.tsx
  src/screen/RegisterScreen/components/AddressInput.tsx
  src/screen/RegisterScreen/components/AddressPicker.tsx
  src/screen/RegisterScreen/components/BirthInput.tsx
  src/screen/RegisterScreen/components/BirthPicker.tsx
  src/screen/RegisterScreen/components/Button.tsx
  src/screen/RegisterScreen/components/GenderInput.tsx
  src/screen/RegisterScreen/components/ProfileImage.tsx
  src/screen/RegisterScreen/components/SubmitButton.tsx
  src/screen/RegisterScreen/components/TextInput.tsx
  src/screen/RegisterScreen/components/Title.tsx
  src/screen/RegisterScreen/index.tsx
  src/screen/WebViewScreen/index.tsx
  src/util/date.ts
  src/util/parseToken.ts
  src/util/storage.ts
  storybook/stories/Button/CircleButton.stories.tsx
  yarn.lock
Labels: feature, UI

#7 chore: android settings
  android/app/src/main/java/com/myapp/MainActivity.java
  patches/react-native-picker+4.3.7.patch
  yarn.lock
Labels: setup

#9 DAISY-19-로그인-버그
  App.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  src/screen/MainScreen/index.tsx
  src/screen/WebViewScreen/index.tsx
  src/util/storage.ts
  yarn.lock
Labels: bug, feature
